const router = require('koa-router')()
const category = require("./category")
const mission = require("./mission")
const file = require("./file")
const uuid = require("./uuid")
const token = require("./token")
const miniUser = require("./miniUser")
const order = require("./order")
const rating = require("./rating")
const role = require("./role")
const user = require("./user")
const price = require("./price")
const money = require("./money")
const payOrder = require("./payOrder")
const question = require("./question")
const protocol = require("./protocol")
const usersig = require("./userSig")
router.prefix("/v1")

module.exports = (app)=>{
    router.use(category.routes(),category.allowedMethods())
    router.use(mission.routes(),mission.allowedMethods())
    router.use(file.routes(),file.allowedMethods())
    router.use(uuid.routes(),uuid.allowedMethods())
    router.use(token.routes(),uuid.allowedMethods())
    router.use(miniUser.routes(),miniUser.allowedMethods())
    router.use(order.routes(),order.allowedMethods())
    router.use(rating.routes(),rating.allowedMethods())
    router.use(role.routes(),role.allowedMethods())
    router.use(user.routes(),user.allowedMethods())
    router.use(price.routes(),price.allowedMethods())
    router.use(money.routes(),money.allowedMethods())
    router.use(payOrder.routes(),payOrder.allowedMethods())
	router.use(question.routes(),question.allowedMethods())
	router.use(protocol.routes(),protocol.allowedMethods())
	router.use(usersig.routes(),usersig.allowedMethods())
    app.use(router.routes(),router.allowedMethods())
}

